name = "agrinetwork"
main = "backend/worker.js"
compatibility_date = "2024-09-01"

account_id = "${CLOUDFLARE_ACCOUNT_ID}"

[[d1_databases]]
binding = "DB"
database_name = "agrinetwork"
database_id = "${D1_DATABASE_ID}"

[[kv_namespaces]]
binding = "NOTIFICATIONS_KV"
id = "${KV_NAMESPACE_ID}"

[vars]
APP_URL = "${APP_URL}"
GEMINI_API_KEY = "${GEMINI_API_KEY}"

[observability.logs]
enabled = true