name = "agrinetwork"
main = "backend/worker.js"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "agrinetwork"
database_id = "your-d1-id-here"

[vars]
APP_URL = "https://your-cloudflare-worker-url.workers.dev"