name: 🚀 Deploy AgriNetwork to Cloudflare Workers

on:
  push:
    branches:
      - main  # Deploy automatically when pushing to main

jobs:
  deploy:
    name: Deploy Worker
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Bun runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📦 Install dependencies
        run: bun install

      - name: ☁️ Deploy to Cloudflare
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}
          KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          APP_URL: ${{ secrets.APP_URL }}